# Generated by Django 5.2 on 2026-05-18 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='รหัสห้อง')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อห้อง')),
                ('room_type', models.CharField(choices=[('MEETING', 'ห้องประชุม'), ('LECTURE', 'ห้องบรรยาย')], max_length=10, verbose_name='ประเภท')),
                ('capacity', models.IntegerField(verbose_name='จำนวนที่นั่ง')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='รูปภาพห้อง (URL)')),
            ],
            options={
                'verbose_name': 'ห้อง',
                'verbose_name_plural': 'ห้อง',
            },
        ),
        migrations.CreateModel(
            name='BlackoutPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อช่วงเวลาปิด เช่น ปิดเทอมภาคฤดูร้อน')),
                ('start_date', models.DateField(verbose_name='วันเริ่มต้น')),
                ('end_date', models.DateField(verbose_name='วันสิ้นสุด')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, help_text='ถ้าไม่เลือกห้อง = ปิดทุกห้องพร้อมกัน', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blackout_periods', to='rooms.room', verbose_name='ห้อง')),
            ],
            options={
                'verbose_name': 'ช่วงเวลาปิดห้อง',
                'verbose_name_plural': 'ช่วงเวลาปิดห้อง',
                'ordering': ['-start_date'],
            },
        ),
    ]
