# Generated by Django 5.2.6 on 2026-04-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='รหัสห้อง')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อห้อง')),
                ('room_type', models.CharField(choices=[('MEETING', 'ห้องประชุม'), ('LECTURE', 'ห้องบรรยาย')], max_length=10, verbose_name='ประเภท')),
                ('capacity', models.IntegerField(verbose_name='จำนวนที่นั่ง')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='รูปภาพห้อง')),
            ],
            options={
                'verbose_name': 'ห้อง',
                'verbose_name_plural': 'ห้อง',
            },
        ),
    ]
