# Generated by Django 5.2.6 on 2026-04-21 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_type', models.CharField(choices=[('TEACHING', 'สอนปกติ/ชดเชย/เสริม'), ('TRAINING', 'จัดอบรม/จัดติว')], max_length=10, verbose_name='วัตถุประสงค์')),
                ('course_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสวิชา')),
                ('course_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อวิชา')),
                ('program', models.CharField(blank=True, choices=[('NORMAL', 'ปริญญาตรีภาคปกติ'), ('MASTER', 'ปริญญาโท'), ('TEP_TEPE', 'TEP-TEPE'), ('TU_PINE', 'TU-PINE')], max_length=20, null=True, verbose_name='หลักสูตร')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อเรื่อง/หัวข้ออบรม')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่มต้น')),
                ('end_date', models.DateField(verbose_name='วันที่สิ้นสุด')),
                ('days_of_week', models.CharField(help_text='เก็บเป็นตัวเลข 0-4 คั่นด้วยเครื่องหมายจุลภาค', max_length=50, verbose_name='วันที่ใช้งานในสัปดาห์')),
                ('start_time', models.TimeField(verbose_name='เวลาเริ่มต้น')),
                ('end_time', models.TimeField(verbose_name='เวลาสิ้นสุด')),
                ('status', models.CharField(choices=[('PENDING', 'รอการอนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ปฏิเสธ'), ('CANCELLED', 'ยกเลิกโดยผู้จอง')], default='PENDING', max_length=10, verbose_name='สถานะการจอง')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='เหตุผลในกรณีปฏิเสธ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จอง')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room', verbose_name='ห้องที่เลือก')),
            ],
            options={
                'verbose_name': 'การจอง',
                'verbose_name_plural': 'การจอง',
                'ordering': ['-created_at'],
            },
        ),
    ]
