# Generated by Codex on 2026-05-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อประกาศ')),
                ('body', models.TextField(verbose_name='รายละเอียด')),
                ('is_active', models.BooleanField(default=True, verbose_name='แสดงบน Dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้างประกาศ')),
            ],
            options={
                'verbose_name': 'ประกาศ',
                'verbose_name_plural': 'ประกาศ',
                'ordering': ['-created_at'],
            },
        ),
    ]
