# Generated by Django 5.2.6 on 2026-04-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='กลุ่มเรียน (Section)'),
        ),
    ]
